LightJason - AgentSpeak(L++): org.lightjason.agentspeak.action.buildin.graph.CAdjacencyMatrix Class Reference
org.lightjason.agentspeak.action.buildin.graph.CAdjacencyMatrix Class Reference
creates from a graph the adjacency matrix.
Public Member Functions
final IFuzzyValue< Boolean > execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
defines a plan-body operation
final int minimalArgumentNumber ()
minimum number of arguments
Public Member Functions inherited from org.lightjason.agentspeak.action.buildin.IBuildinAction
final IPath name ()
returns the name with path of the action
Public Member Functions inherited from org.lightjason.agentspeak.action.IBaseAction
final boolean equals (final Object p_object)
final int hashCode ()
final double score (final IAgent<?> p_agent)
returns the scoring value of the execution structure
final String toString ()
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Static Private Member Functions
static Pair< DoubleMatrix2D,
Collection<?> > apply (final AbstractGraph< Object, Object > p_graph, final Map<?, Number > p_cost, final double p_defaultcost, final EType p_type)
converts a graph into an adjacency matrix
Additional Inherited Members
Protected Member Functions inherited from org.lightjason.agentspeak.action.buildin.IBuildinAction
IBuildinAction ()
ctor
IBuildinAction (final int p_length)
ctor
Static Protected Attributes inherited from org.lightjason.agentspeak.action.buildin.IBuildinAction
static final Logger LOGGER = CCommon.logger(IBuildinAction.class)
logger
Detailed Description
The action converts graphs into a matrix based on a cost-map, the first argument can be a string with dense or sparse for defining the returned matrix, after that a cost-map cann be set or a fixed numerical value for defining the cost of an edge, all other arguments are graphs, for each graph the matrix and vertex list is returned, the action never fails
[M1|V1|M2|V2] = graph/adjacencymatrix("dense|sparse", CostMap, Graph1, Graph2);
[M3|V3|M4|V4] = graph/adjacencymatrix(CostMap, Graph1, Graph2);
[M1|V1|M2|V2] = graph/adjacencymatrix("dense|sparse", 1, Graph1, Graph2);
[M3|V3|M4|V4] = graph/adjacencymatrix(1, Graph1, Graph2);
Note
the cost-map does not need an entry for each edge non-existing edges have got on default zero costs with 1
See Also
https://en.wikipedia.org/wiki/Adjacency_matrix
Definition at line 74 of file CAdjacencyMatrix.java.
Member Function Documentation
static Pair<DoubleMatrix2D, Collection<?> > org.lightjason.agentspeak.action.buildin.graph.CAdjacencyMatrix.apply (final AbstractGraph< Object, Object > p_graph, final Map<?, Number > p_cost, final double p_defaultcost, final EType p_type) static private
Parameters
p_graph graph
p_cost map with edges and costs
p_defaultcost default cost value (on non-existing map values)
p_type matrix type
Returns
pair of double matrix and vertices
Definition at line 144 of file CAdjacencyMatrix.java.
Referenced by org.lightjason.agentspeak.action.buildin.graph.CAdjacencyMatrix.execute().
final IFuzzyValue<Boolean> org.lightjason.agentspeak.action.buildin.graph.CAdjacencyMatrix.execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
Parameters
p_context current execution context
p_parallel parallel execution
p_argument parameter of the action
p_return return values
p_annotation annotation
Returns
fuzzy boolean
Implements org.lightjason.agentspeak.language.execution.IExecution.
Definition at line 83 of file CAdjacencyMatrix.java.
References org.lightjason.agentspeak.action.buildin.graph.CAdjacencyMatrix.apply(), org.lightjason.agentspeak.action.buildin.math.blas.EType.DENSE, org.lightjason.agentspeak.language.CCommon.rawvalueAssignableTo(), and org.lightjason.agentspeak.action.buildin.math.blas.EType.SPARSE.
final int org.lightjason.agentspeak.action.buildin.graph.CAdjacencyMatrix.minimalArgumentNumber ()
Returns
number of minimal arguments
Implements org.lightjason.agentspeak.action.IAction.
Definition at line 77 of file CAdjacencyMatrix.java.