LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.CCommon Class Reference
org.lightjason.agentspeak.language.CCommon Class Reference
common structure for execution definition
Classes
enum ECompression
compression algorithm
Static Public Member Functions
static Stream< ITerm > flatcollection (final Collection<?extends ITerm > p_terms)
flat term-in-term collection into a straight term list
static byte[] getBytes (final List< ITerm > p_input) throws UnsupportedEncodingException
flats and concat the term list
static Hasher getTermHashing ()
returns the hasing function for term data
static IContext instantiate (final IInstantiable p_instance, final IAgent<?> p_agent, final Stream< IVariable<?>> p_variable)
creates the instantiate execution context with default variables
static Pair< IPlan, IContext > instantiateplan (final IPlan p_plan, final double p_fail, final double p_success, final IAgent<?> p_agent, final Set< IVariable<?>> p_variables)
instantiate a plan with context and plan-specific variables
static double levenshtein (final String p_first, final String p_second, final double p_insertweight, final double p_replaceweight, final double p_deleteweight)
calculates the levenshtein distance
static double min (final double p_first, final double p_second, final double p_third)
returns the minimum of three elemens
static double ncd (final ECompression p_compression, final String p_first, final String p_second)
normalized-compression-distance
static< T > boolean rawvalueAssignableTo (final T p_value, final Class<?>...p_class)
checks a term value for assignable class
static Stream< ITerm > recursiveliteral (final Stream< ILiteral > p_input)
recursive stream of literal values
static Stream< ITerm > recursiveterm (final Stream< ITerm > p_input)
recursive stream of term values
static List< ITerm > replaceFromContext (final IContext p_context, final Collection<?extends ITerm > p_terms)
replace variables with context variables
static ITerm replaceFromContext (final IContext p_context, final ITerm p_term)
replace variable with context variable other values will be passed without context access
static Pair< Boolean, Set
< IVariable<?> > > unifytrigger (final IUnifier p_unifier, final ITrigger p_source, final ITrigger p_target)
unifies trigger and creates the set of variables
static IContext updatecontext (final IContext p_context, final Stream< IVariable<?>> p_unifiedvariables)
updates within an instance context all variables of the stream
static Map< IVariable<?>, Integer > variablefrequency (final ILiteral p_literal)
consts the variables within a literal
Private Member Functions
CCommon ()
private ctor - avoid instantiation
Static Private Member Functions
static double compress (final ECompression p_compression, final String p_input)
compression algorithm
static Stream< ITerm > flattenToStream (final Collection<?> p_list)
Detailed Description
Definition at line 71 of file language/CCommon.java.
Constructor & Destructor Documentation
org.lightjason.agentspeak.language.CCommon.CCommon () private
Definition at line 76 of file language/CCommon.java.
Member Function Documentation
static double org.lightjason.agentspeak.language.CCommon.compress (final ECompression p_compression, final String p_input) static private
Parameters
p_compression compression algorithm
p_input input string
Returns
number of compression bytes
Warning
counting stream returns the correct number of bytes after flushing
Definition at line 411 of file language/CCommon.java.
Referenced by org.lightjason.agentspeak.language.CCommon.ncd().
static Stream<ITerm> org.lightjason.agentspeak.language.CCommon.flatcollection (final Collection<?extends ITerm > p_terms) static
Parameters
p_terms term collection
Returns
flat term stream
Definition at line 261 of file language/CCommon.java.
References org.lightjason.agentspeak.language.CCommon.flattenToStream().
Referenced by org.lightjason.agentspeak.action.buildin.agent.CClearBeliefbase.execute(), org.lightjason.agentspeak.action.buildin.datetime.IDateTime.execute(), and org.lightjason.agentspeak.language.CCommon.getBytes().
static Stream<ITerm> org.lightjason.agentspeak.language.CCommon.flattenToStream (final Collection<?> p_list) static private
Definition at line 312 of file language/CCommon.java.
References org.lightjason.agentspeak.language.CCommon.flattenToStream().
Referenced by org.lightjason.agentspeak.language.CCommon.flatcollection(), and org.lightjason.agentspeak.language.CCommon.flattenToStream().
static byte [] org.lightjason.agentspeak.language.CCommon.getBytes (final List< ITerm > p_input) throws UnsupportedEncodingException static
Parameters
p_input input term list
Returns
byte sequence with UTF-8 encoding
Exceptions
UnsupportedEncodingException is thrown on wrong encoding type
Definition at line 274 of file language/CCommon.java.
References org.lightjason.agentspeak.language.CCommon.flatcollection(), and org.lightjason.agentspeak.language.CCommon.getBytes().
Referenced by org.lightjason.agentspeak.language.CCommon.getBytes().
static Hasher org.lightjason.agentspeak.language.CCommon.getTermHashing () static
Returns
hasher
Definition at line 327 of file language/CCommon.java.
static IContext org.lightjason.agentspeak.language.CCommon.instantiate (final IInstantiable p_instance, final IAgent<?> p_agent, final Stream< IVariable<?>> p_variable) static
Parameters
p_instance instance object
p_agent agent
p_variable variable stream
Returns
context object
Definition at line 103 of file language/CCommon.java.
static Pair<IPlan, IContext> org.lightjason.agentspeak.language.CCommon.instantiateplan (final IPlan p_plan, final double p_fail, final double p_success, final IAgent<?> p_agent, final Set< IVariable<?>> p_variables) static
Parameters
p_plan plan
p_fail fail runs
p_success successful runs
p_agent agent
p_variables instantiated variables
Returns
pair of plan and context object
Definition at line 157 of file language/CCommon.java.
static double org.lightjason.agentspeak.language.CCommon.levenshtein (final String p_first, final String p_second, final double p_insertweight, final double p_replaceweight, final double p_deleteweight) static
Parameters
p_first first string
p_second second string
p_insertweight inserting weight
p_replaceweight replace weight
p_deleteweight delete weight
Returns
distance
See Also
https://en.wikibooks.org/wiki/Algorithm_Implementation/Strings/Levenshtein_distance#Java
Definition at line 345 of file language/CCommon.java.
References org.lightjason.agentspeak.language.CCommon.min().
static double org.lightjason.agentspeak.language.CCommon.min (final double p_first, final double p_second, final double p_third) static
Parameters
p_first first value
p_second second value
p_third third value
Returns
minimum
Definition at line 381 of file language/CCommon.java.
Referenced by org.lightjason.agentspeak.language.CCommon.levenshtein().
static double org.lightjason.agentspeak.language.CCommon.ncd (final ECompression p_compression, final String p_first, final String p_second) static
Parameters
p_compression compression algorithm
p_first first string
p_second second string
Returns
distance in [0,1]
Definition at line 395 of file language/CCommon.java.
References org.lightjason.agentspeak.language.CCommon.compress().
static <T> boolean org.lightjason.agentspeak.language.CCommon.rawvalueAssignableTo (final T p_value, final Class<?>... p_class) static
Parameters
p_value any value type
p_class assignable class
Returns
term value or raw value
Definition at line 208 of file language/CCommon.java.
Referenced by org.lightjason.agentspeak.action.buildin.math.blas.CElementWise.apply(), org.lightjason.agentspeak.action.buildin.string.CLevenshtein.execute(), org.lightjason.agentspeak.action.buildin.graph.CSpanningTree.execute(), org.lightjason.agentspeak.action.buildin.math.statistic.CClearStatistic.execute(), org.lightjason.agentspeak.action.buildin.math.bit.vector.CClear.execute(), org.lightjason.agentspeak.action.buildin.math.blas.CMultiply.execute(), org.lightjason.agentspeak.action.buildin.math.blas.vector.CCreate.execute(), org.lightjason.agentspeak.action.buildin.math.blas.vector.CFromList.execute(), org.lightjason.agentspeak.action.buildin.math.blas.matrix.CCreate.execute(), org.lightjason.agentspeak.action.buildin.math.blas.matrix.CAssign.execute(), org.lightjason.agentspeak.action.buildin.math.blas.vector.CAssign.execute(), org.lightjason.agentspeak.action.buildin.math.statistic.CMultipleStatisticValue.execute(), org.lightjason.agentspeak.action.buildin.math.bit.vector.CToBlas.execute(), org.lightjason.agentspeak.action.buildin.math.statistic.CAddStatisticValue.execute(), org.lightjason.agentspeak.action.buildin.math.statistic.CSingleStatisticValue.execute(), org.lightjason.agentspeak.action.buildin.math.blas.matrix.CParse.execute(), org.lightjason.agentspeak.action.buildin.graph.CAdjacencyMatrix.execute(), org.lightjason.agentspeak.action.buildin.datetime.IDateTime.getdatetime(), org.lightjason.agentspeak.action.buildin.math.blas.matrix.CSolve.result(), and org.lightjason.agentspeak.action.buildin.collection.CSize.size().
static Stream<ITerm> org.lightjason.agentspeak.language.CCommon.recursiveliteral (final Stream< ILiteral > p_input) static
Parameters
p_input term stream
Returns
term stream
Note
annotations cannot use annotation within
Definition at line 300 of file language/CCommon.java.
References org.lightjason.agentspeak.language.CCommon.recursiveterm().
Referenced by org.lightjason.agentspeak.agent.unify.CUnifier.literal(), org.lightjason.agentspeak.language.CCommon.variablefrequency(), org.lightjason.agentspeak.language.instantiable.rule.CRule.variables(), org.lightjason.agentspeak.language.execution.action.unify.CDefaultUnify.variables(), and org.lightjason.agentspeak.language.instantiable.plan.CPlan.variables().
static Stream<ITerm> org.lightjason.agentspeak.language.CCommon.recursiveterm (final Stream< ITerm > p_input) static
Parameters
p_input term stream
Returns
term stream
Definition at line 287 of file language/CCommon.java.
References org.lightjason.agentspeak.language.CCommon.recursiveterm().
Referenced by org.lightjason.agentspeak.agent.unify.CUnifier.literal(), org.lightjason.agentspeak.language.CCommon.recursiveliteral(), org.lightjason.agentspeak.language.CCommon.recursiveterm(), org.lightjason.agentspeak.language.CCommon.variablefrequency(), and org.lightjason.agentspeak.language.instantiable.plan.CPlan.variables().
static List<ITerm> org.lightjason.agentspeak.language.CCommon.replaceFromContext (final IContext p_context, final Collection<?extends ITerm > p_terms) static
Parameters
p_context execution context
p_terms replacing term list
Returns
result term list
Definition at line 226 of file language/CCommon.java.
References org.lightjason.agentspeak.language.CCommon.replaceFromContext().
Referenced by org.lightjason.agentspeak.language.execution.unaryoperator.CDecrement< T extends Number >.execute(), org.lightjason.agentspeak.language.execution.unaryoperator.CIncrement< T extends Number >.execute(), and org.lightjason.agentspeak.language.CCommon.replaceFromContext().
static ITerm org.lightjason.agentspeak.language.CCommon.replaceFromContext (final IContext p_context, final ITerm p_term) static
Parameters
p_context execution context
p_term term
Returns
replaces variable object
Definition at line 239 of file language/CCommon.java.
References org.lightjason.agentspeak.language.ITerm.fqnfunctor().
static Pair<Boolean, Set<IVariable<?> > > org.lightjason.agentspeak.language.CCommon.unifytrigger (final IUnifier p_unifier, final ITrigger p_source, final ITrigger p_target) static
Note
target trigger literal must be cloned to avoid variable overwriting
Parameters
p_unifier unifier
p_source input trigger (with values)
p_target trigger (of a plan / rule)
Returns
pair of valid unification and unified variables
Definition at line 131 of file language/CCommon.java.
References org.lightjason.agentspeak.language.instantiable.plan.trigger.ITrigger.getLiteral().
static IContext org.lightjason.agentspeak.language.CCommon.updatecontext (final IContext p_context, final Stream< IVariable<?>> p_unifiedvariables) static
Parameters
p_context context
p_unifiedvariables unified variables as stream
Returns
context reference
Definition at line 89 of file language/CCommon.java.
static Map<IVariable<?>, Integer> org.lightjason.agentspeak.language.CCommon.variablefrequency (final ILiteral p_literal) static
Parameters
p_literal literal
Returns
map with frequency
Definition at line 187 of file language/CCommon.java.
References org.lightjason.agentspeak.language.ILiteral.annotations(), org.lightjason.agentspeak.language.ILiteral.orderedvalues(), org.lightjason.agentspeak.language.CCommon.recursiveliteral(), and org.lightjason.agentspeak.language.CCommon.recursiveterm().