LightJason - AgentSpeak(L++): org.lightjason.agentspeak.language.execution.IExecution Interface Reference
org.lightjason.agentspeak.language.execution.IExecution Interface Reference
internal execution interface
Public Member Functions
IFuzzyValue< Boolean > execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
defines a plan-body operation
double score (final IAgent<?> p_agent)
returns the scoring value of the execution structure
Stream< IVariable<?> > variables ()
returns a stream with all used variables
Detailed Description
Definition at line 38 of file IExecution.java.
Member Function Documentation
IFuzzyValue<Boolean> org.lightjason.agentspeak.language.execution.IExecution.execute (final IContext p_context, final boolean p_parallel, final List< ITerm > p_argument, final List< ITerm > p_return, final List< ITerm > p_annotation)
Parameters
p_context current execution context
p_parallel parallel execution
p_argument parameter of the action
p_return return values
p_annotation annotation
Returns
fuzzy boolean
Implemented in org.lightjason.agentspeak.agent.IBaseHanoiTowers.CTowerPop, org.lightjason.agentspeak.agent.IBaseHanoiTowers.CTowerPush, org.lightjason.agentspeak.agent.TestCAgentExecution.CLog, org.lightjason.agentspeak.agent.IBaseHanoiTowers.CTowerSize, org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper, org.lightjason.agentspeak.agent.TestCAgentExecution.CStop, org.lightjason.agentspeak.agent.IBaseHanoiTowers.CStop, org.lightjason.agentspeak.action.buildin.math.statistic.CCreateDistribution, org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >, org.lightjason.agentspeak.language.instantiable.plan.CPlan, org.lightjason.agentspeak.language.instantiable.IBaseInstantiable, org.lightjason.agentspeak.action.buildin.generic.CPrint, org.lightjason.agentspeak.action.binding.CMethodAction, org.lightjason.agentspeak.language.execution.action.CRawAction< T >, org.lightjason.agentspeak.language.instantiable.rule.CRulePlaceholder, org.lightjason.agentspeak.action.buildin.math.linearprogram.CSolve, org.lightjason.agentspeak.language.execution.action.CProxyAction, org.lightjason.agentspeak.action.buildin.storage.CRemove, org.lightjason.agentspeak.action.buildin.storage.CAdd, org.lightjason.agentspeak.action.buildin.graph.CAdjacencyMatrix, org.lightjason.agentspeak.action.buildin.storage.CExists, org.lightjason.agentspeak.action.buildin.storage.CClear, org.lightjason.agentspeak.action.buildin.math.interpolate.CCreate, org.lightjason.agentspeak.action.buildin.math.linearprogram.CEquationConstraint, org.lightjason.agentspeak.action.buildin.math.linearprogram.CValueConstraint, org.lightjason.agentspeak.action.buildin.math.statistic.CRandomSimple, org.lightjason.agentspeak.action.buildin.math.statistic.CCreateStatistic, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CParse, org.lightjason.agentspeak.action.buildin.math.linearprogram.CCreate, org.lightjason.agentspeak.action.buildin.crypto.CHash, org.lightjason.agentspeak.action.buildin.graph.CCreate, org.lightjason.agentspeak.action.buildin.generic.type.CIs, org.lightjason.agentspeak.action.buildin.math.bit.vector.CToBlas, org.lightjason.agentspeak.action.buildin.math.statistic.CAddStatisticValue, org.lightjason.agentspeak.action.buildin.math.statistic.CRandomSample, org.lightjason.agentspeak.action.buildin.math.statistic.CSingleStatisticValue, org.lightjason.agentspeak.action.buildin.collection.multimap.CCreate, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CAssign, org.lightjason.agentspeak.action.buildin.math.blas.vector.CAssign, org.lightjason.agentspeak.action.buildin.math.statistic.CMultipleStatisticValue, org.lightjason.agentspeak.action.buildin.collection.list.CSymmetricDifference, org.lightjason.agentspeak.action.buildin.collection.map.CCreate, org.lightjason.agentspeak.action.buildin.collection.map.CGet, org.lightjason.agentspeak.action.buildin.math.bit.vector.CRange, org.lightjason.agentspeak.action.buildin.math.bit.vector.CToList, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CCreate, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CGraphLaplacian, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CNormalizedGraphLaplacian, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CPower, org.lightjason.agentspeak.action.buildin.math.blas.vector.CFromList, org.lightjason.agentspeak.action.buildin.math.interpolate.CMultipleInterpolate, org.lightjason.agentspeak.action.buildin.math.interpolate.CSingleInterpolate, org.lightjason.agentspeak.action.buildin.math.shape.CInCircle, org.lightjason.agentspeak.action.buildin.math.shape.CInRectangle, org.lightjason.agentspeak.language.execution.unaryoperator.CDecrement< T extends Number >, org.lightjason.agentspeak.language.execution.unaryoperator.CIncrement< T extends Number >, org.lightjason.agentspeak.action.buildin.agent.CGetPlan, org.lightjason.agentspeak.action.buildin.collection.list.CCreate, org.lightjason.agentspeak.action.buildin.collection.list.CZip, org.lightjason.agentspeak.action.buildin.math.bit.matrix.CBoolValue, org.lightjason.agentspeak.action.buildin.math.bit.matrix.CNumericValue, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CGet, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CSingularValue, org.lightjason.agentspeak.action.buildin.math.blas.vector.CCreate, org.lightjason.agentspeak.action.buildin.math.blas.vector.CDotProduct, org.lightjason.agentspeak.action.buildin.math.shape.CInTriangle, org.lightjason.agentspeak.action.buildin.collection.multimap.CGet, org.lightjason.agentspeak.action.buildin.graph.CDistancePath, org.lightjason.agentspeak.action.buildin.graph.CShortestPath, org.lightjason.agentspeak.action.buildin.math.bit.vector.CNumericValue, org.lightjason.agentspeak.action.buildin.math.bit.vector.CSet, org.lightjason.agentspeak.action.buildin.math.blas.CMultiply, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CColumn, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CEigen, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CInfinityNorm, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CRow, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CToList, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CTwoNorm, org.lightjason.agentspeak.action.buildin.math.blas.vector.CToList, org.lightjason.agentspeak.action.buildin.math.statistic.ISelection, org.lightjason.agentspeak.action.buildin.collection.list.CGet, org.lightjason.agentspeak.action.buildin.collection.list.CIntersect, org.lightjason.agentspeak.action.buildin.collection.list.CRange, org.lightjason.agentspeak.action.buildin.collection.list.CUnique, org.lightjason.agentspeak.action.buildin.collection.map.CValues, org.lightjason.agentspeak.action.buildin.collection.multimap.CAsMap, org.lightjason.agentspeak.action.buildin.collection.multimap.CValues, org.lightjason.agentspeak.action.buildin.collection.tuple.CCreate, org.lightjason.agentspeak.action.buildin.generic.type.CTo, org.lightjason.agentspeak.action.buildin.math.bit.matrix.CCreate, org.lightjason.agentspeak.action.buildin.math.bit.vector.CBoolValue, org.lightjason.agentspeak.action.buildin.math.bit.vector.CClear, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CCondition, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CDeterminant, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CInvert, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CMatrixNorm, org.lightjason.agentspeak.action.buildin.math.blas.matrix.COneNorm, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CRank, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CSet, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CSubMatrix, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CTrace, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CTranspose, org.lightjason.agentspeak.action.buildin.math.blas.vector.CGet, org.lightjason.agentspeak.action.buildin.math.blas.vector.CSet, org.lightjason.agentspeak.language.execution.expression.numerical.CAdditive, org.lightjason.agentspeak.language.execution.expression.numerical.CMultiplicative, org.lightjason.agentspeak.language.execution.expression.numerical.CRelational, org.lightjason.agentspeak.action.buildin.collection.list.CComplement, org.lightjason.agentspeak.action.buildin.collection.list.CReverse, org.lightjason.agentspeak.action.buildin.collection.list.CUnion, org.lightjason.agentspeak.action.buildin.collection.map.CKeys, org.lightjason.agentspeak.action.buildin.collection.map.CRemove, org.lightjason.agentspeak.action.buildin.collection.multimap.CKeys, org.lightjason.agentspeak.action.buildin.collection.tuple.CFlat, org.lightjason.agentspeak.action.buildin.generic.type.CCreateLiteral, org.lightjason.agentspeak.action.buildin.generic.type.CIsNull, org.lightjason.agentspeak.action.buildin.graph.CSpanningTree, org.lightjason.agentspeak.action.buildin.math.bit.matrix.CCopy, org.lightjason.agentspeak.action.buildin.math.bit.matrix.CSize, org.lightjason.agentspeak.action.buildin.math.bit.vector.CCopy, org.lightjason.agentspeak.action.buildin.math.bit.vector.CCreate, org.lightjason.agentspeak.action.buildin.math.bit.vector.CSize, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CColumns, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CCopy, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CRows, org.lightjason.agentspeak.action.buildin.math.blas.vector.CCopy, org.lightjason.agentspeak.action.buildin.math.statistic.CClearStatistic, org.lightjason.agentspeak.language.execution.expression.numerical.CComparable, org.lightjason.agentspeak.language.execution.expression.numerical.CPower, org.lightjason.agentspeak.action.buildin.agent.CBeliefList, org.lightjason.agentspeak.action.buildin.collection.list.CSubList, org.lightjason.agentspeak.action.buildin.crypto.CDecrypt, org.lightjason.agentspeak.action.buildin.crypto.CEncrypt, org.lightjason.agentspeak.action.buildin.datetime.IPlusMinus, org.lightjason.agentspeak.action.buildin.generic.type.CIsNumeric, org.lightjason.agentspeak.action.buildin.generic.type.ICast, org.lightjason.agentspeak.action.buildin.math.bit.matrix.CColumns, org.lightjason.agentspeak.action.buildin.math.bit.matrix.CDimension, org.lightjason.agentspeak.action.buildin.math.bit.matrix.CFalseCount, org.lightjason.agentspeak.action.buildin.math.bit.matrix.CNot, org.lightjason.agentspeak.action.buildin.math.bit.matrix.CRows, org.lightjason.agentspeak.action.buildin.math.bit.matrix.CTrueCount, org.lightjason.agentspeak.action.buildin.math.bit.matrix.IRowColumn, org.lightjason.agentspeak.action.buildin.math.bit.vector.CFalseCount, org.lightjason.agentspeak.action.buildin.math.bit.vector.CNot, org.lightjason.agentspeak.action.buildin.math.bit.vector.CTrueCount, org.lightjason.agentspeak.action.buildin.math.blas.CElementWise, org.lightjason.agentspeak.action.buildin.math.blas.CSize, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CDimension, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CNonZero, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CSum, org.lightjason.agentspeak.action.buildin.math.blas.vector.CNonZero, org.lightjason.agentspeak.action.buildin.math.blas.vector.CSum, org.lightjason.agentspeak.language.execution.expression.CAtom, org.lightjason.agentspeak.action.buildin.agent.CPlanStatistic, org.lightjason.agentspeak.action.buildin.agent.CRemovePlan, org.lightjason.agentspeak.action.buildin.collection.list.CIsEmpty, org.lightjason.agentspeak.action.buildin.collection.map.CPut, org.lightjason.agentspeak.action.buildin.collection.map.CPutIfAbsent, org.lightjason.agentspeak.action.buildin.collection.multimap.CPut, org.lightjason.agentspeak.action.buildin.generic.type.CIsString, org.lightjason.agentspeak.action.buildin.math.blas.matrix.CSolve, org.lightjason.agentspeak.language.execution.expression.CProxyReturnExpression< T extends IExecution >, org.lightjason.agentspeak.language.execution.expression.logical.CBinary, org.lightjason.agentspeak.language.execution.expression.logical.CUnary, org.lightjason.agentspeak.action.buildin.collection.list.CFlatConcat, org.lightjason.agentspeak.action.buildin.collection.list.CRemove, org.lightjason.agentspeak.action.buildin.collection.list.CSet, org.lightjason.agentspeak.action.buildin.crypto.CCreateKey, org.lightjason.agentspeak.action.buildin.datetime.IBetween, org.lightjason.agentspeak.action.buildin.datetime.IDateTime, org.lightjason.agentspeak.action.buildin.string.CBase64Decode, org.lightjason.agentspeak.action.buildin.string.CLevenshtein, org.lightjason.agentspeak.action.buildin.graph.CInEdges, org.lightjason.agentspeak.action.buildin.graph.CNeighbors, org.lightjason.agentspeak.action.buildin.graph.COutEdges, org.lightjason.agentspeak.action.buildin.math.bit.matrix.IOperator, org.lightjason.agentspeak.action.buildin.math.bit.vector.IOperator, org.lightjason.agentspeak.action.buildin.math.CSigmoid, org.lightjason.agentspeak.action.buildin.math.CStirling, org.lightjason.agentspeak.action.buildin.bool.CEqual, org.lightjason.agentspeak.action.buildin.bool.CNotEqual, org.lightjason.agentspeak.action.buildin.datetime.CBuild, org.lightjason.agentspeak.action.buildin.graph.CFindEdgeSet, org.lightjason.agentspeak.action.buildin.graph.CNeighborsCount, org.lightjason.agentspeak.action.buildin.math.bit.matrix.CToVector, org.lightjason.agentspeak.action.buildin.math.CBinomial, org.lightjason.agentspeak.action.buildin.math.CMaxIndex, org.lightjason.agentspeak.action.buildin.math.CMinIndex, org.lightjason.agentspeak.action.buildin.math.CPrimeFactors, org.lightjason.agentspeak.action.buildin.string.CNCD, org.lightjason.agentspeak.action.buildin.agent.CPlanList, org.lightjason.agentspeak.action.buildin.bool.CAllMatch, org.lightjason.agentspeak.action.buildin.bool.CAnyMatch, org.lightjason.agentspeak.action.buildin.collection.CSize, org.lightjason.agentspeak.action.buildin.generic.type.IParse, org.lightjason.agentspeak.action.buildin.graph.CContainsEdge, org.lightjason.agentspeak.action.buildin.graph.CContainsVertex, org.lightjason.agentspeak.action.buildin.graph.CEndPoint, org.lightjason.agentspeak.action.buildin.graph.CIncidentVertices, org.lightjason.agentspeak.action.buildin.graph.CIsIncident, org.lightjason.agentspeak.action.buildin.graph.CIsNeighbor, org.lightjason.agentspeak.action.buildin.graph.CIsPredecessor, org.lightjason.agentspeak.action.buildin.graph.CIsSuccessor, org.lightjason.agentspeak.action.buildin.graph.COpposite, org.lightjason.agentspeak.action.buildin.graph.CPredecessorCount, org.lightjason.agentspeak.action.buildin.graph.CSuccessorCount, org.lightjason.agentspeak.action.buildin.math.bit.matrix.CHammingDistance, org.lightjason.agentspeak.action.buildin.math.bit.vector.CHammingDistance, org.lightjason.agentspeak.action.buildin.math.CIsPrime, org.lightjason.agentspeak.action.buildin.math.CNextPrime, org.lightjason.agentspeak.action.buildin.string.CBase64Encode, org.lightjason.agentspeak.action.buildin.string.CReplace, org.lightjason.agentspeak.action.buildin.agent.CAddPlan, org.lightjason.agentspeak.action.buildin.bool.CAnd, org.lightjason.agentspeak.action.buildin.bool.CNot, org.lightjason.agentspeak.action.buildin.bool.COr, org.lightjason.agentspeak.action.buildin.bool.CXor, org.lightjason.agentspeak.action.buildin.graph.CAddEdge, org.lightjason.agentspeak.action.buildin.graph.CDegree, org.lightjason.agentspeak.action.buildin.graph.CEdges, org.lightjason.agentspeak.action.buildin.graph.CFindEdge, org.lightjason.agentspeak.action.buildin.graph.CIncidentCount, org.lightjason.agentspeak.action.buildin.graph.CInDegree, org.lightjason.agentspeak.action.buildin.graph.COutDegree, org.lightjason.agentspeak.action.buildin.graph.CRemoveEdge, org.lightjason.agentspeak.action.buildin.graph.CRemoveVertex, org.lightjason.agentspeak.action.buildin.math.CAverage, org.lightjason.agentspeak.action.buildin.math.CFactorial, org.lightjason.agentspeak.action.buildin.math.CLog, org.lightjason.agentspeak.action.buildin.math.CPow, org.lightjason.agentspeak.action.buildin.math.CRound, org.lightjason.agentspeak.action.buildin.math.CTan, org.lightjason.agentspeak.action.buildin.string.CRandom, org.lightjason.agentspeak.action.buildin.agent.CClearBeliefbase, org.lightjason.agentspeak.action.buildin.agent.CSleep, org.lightjason.agentspeak.action.buildin.generic.CThrow, org.lightjason.agentspeak.action.buildin.graph.CEdgeCount, org.lightjason.agentspeak.action.buildin.graph.CVertexCount, org.lightjason.agentspeak.action.buildin.graph.CVertices, org.lightjason.agentspeak.action.buildin.math.CACos, org.lightjason.agentspeak.action.buildin.math.CASin, org.lightjason.agentspeak.action.buildin.math.CATan, org.lightjason.agentspeak.action.buildin.math.CCeil, org.lightjason.agentspeak.action.buildin.math.CCosh, org.lightjason.agentspeak.action.buildin.math.CDegrees, org.lightjason.agentspeak.action.buildin.math.CExp, org.lightjason.agentspeak.action.buildin.math.CFloor, org.lightjason.agentspeak.action.buildin.math.CGeometricMean, org.lightjason.agentspeak.action.buildin.math.CHarmonicMean, org.lightjason.agentspeak.action.buildin.math.CHypot, org.lightjason.agentspeak.action.buildin.math.CLog10, org.lightjason.agentspeak.action.buildin.math.CMax, org.lightjason.agentspeak.action.buildin.math.CMin, org.lightjason.agentspeak.action.buildin.math.CRadians, org.lightjason.agentspeak.action.buildin.math.CSignum, org.lightjason.agentspeak.action.buildin.math.CSinh, org.lightjason.agentspeak.action.buildin.math.CTanh, org.lightjason.agentspeak.action.buildin.string.CConcat, org.lightjason.agentspeak.action.buildin.string.CContains, org.lightjason.agentspeak.action.buildin.string.CEndsWith, org.lightjason.agentspeak.action.buildin.string.CStartsWith, org.lightjason.agentspeak.action.buildin.agent.CCycleTime, org.lightjason.agentspeak.action.buildin.bool.CCountFalse, org.lightjason.agentspeak.action.buildin.graph.CAddVertex, org.lightjason.agentspeak.action.buildin.math.CAbs, org.lightjason.agentspeak.action.buildin.math.CCos, org.lightjason.agentspeak.action.buildin.math.CSin, org.lightjason.agentspeak.action.buildin.math.CSqrt, org.lightjason.agentspeak.action.buildin.string.CLower, org.lightjason.agentspeak.action.buildin.string.CReverse, org.lightjason.agentspeak.action.buildin.string.CSize, org.lightjason.agentspeak.action.buildin.string.CUpper, org.lightjason.agentspeak.action.buildin.bool.CCountTrue, org.lightjason.agentspeak.action.buildin.math.CSum, org.lightjason.agentspeak.action.buildin.rest.CJsonList, org.lightjason.agentspeak.action.buildin.rest.CJsonObject, and org.lightjason.agentspeak.action.buildin.rest.CXMLObject.
Referenced by org.lightjason.agentspeak.language.execution.action.CRepair.execute(), org.lightjason.agentspeak.language.execution.expression.logical.CUnary.execute(), org.lightjason.agentspeak.language.execution.action.CTernaryOperation.execute(), org.lightjason.agentspeak.language.execution.action.CLambdaExpression.execute(), org.lightjason.agentspeak.language.execution.expression.IBaseBinary.executearguments(), and org.lightjason.agentspeak.language.execution.action.CRawAction< T >.getTypedResult().
double org.lightjason.agentspeak.language.execution.IExecution.score (final IAgent<?> p_agent)
Parameters
p_agent agent for which calculates the score value
Returns
score value
Implemented in org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper, org.lightjason.agentspeak.language.instantiable.plan.CPlan, org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >, org.lightjason.agentspeak.language.execution.expression.IBaseBinary, org.lightjason.agentspeak.language.instantiable.rule.CRulePlaceholder, org.lightjason.agentspeak.language.execution.action.CProxyAction, org.lightjason.agentspeak.language.instantiable.IBaseInstantiable, org.lightjason.agentspeak.language.execution.unaryoperator.CDecrement< T extends Number >, org.lightjason.agentspeak.language.execution.unaryoperator.CIncrement< T extends Number >, org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >, org.lightjason.agentspeak.language.execution.expression.CProxyReturnExpression< T extends IExecution >, org.lightjason.agentspeak.language.execution.expression.IBaseUnary, org.lightjason.agentspeak.language.execution.expression.CAtom, and org.lightjason.agentspeak.action.IBaseAction.
Stream<IVariable<?> > org.lightjason.agentspeak.language.execution.IExecution.variables ()
Returns
variable stream (variables will be cloned on instantiation)
Implemented in org.lightjason.agentspeak.language.execution.action.CProxyAction.CActionWrapper, org.lightjason.agentspeak.language.instantiable.plan.CPlan, org.lightjason.agentspeak.language.execution.action.CProxyAction.CTermWrapper< T extends ITerm >, org.lightjason.agentspeak.language.execution.expression.IBaseBinary, org.lightjason.agentspeak.language.instantiable.IBaseInstantiable, org.lightjason.agentspeak.language.execution.action.CProxyAction, org.lightjason.agentspeak.language.instantiable.rule.CRulePlaceholder, org.lightjason.agentspeak.language.execution.expression.IBaseUnary, org.lightjason.agentspeak.language.instantiable.rule.CRule, org.lightjason.agentspeak.language.execution.unaryoperator.CDecrement< T extends Number >, org.lightjason.agentspeak.language.execution.unaryoperator.CIncrement< T extends Number >, org.lightjason.agentspeak.language.execution.action.IBaseExecution< T >, org.lightjason.agentspeak.language.execution.expression.CProxyReturnExpression< T extends IExecution >, org.lightjason.agentspeak.language.execution.expression.CAtom, org.lightjason.agentspeak.action.IBaseAction, and org.lightjason.agentspeak.language.execution.action.CRawAction< T >.
Referenced by org.lightjason.agentspeak.language.execution.action.CLambdaExpression.getLocalContext(), org.lightjason.agentspeak.language.execution.action.CRepair.variables(), org.lightjason.agentspeak.language.execution.action.CTernaryOperation.variables(), org.lightjason.agentspeak.language.instantiable.IBaseInstantiable.variables(), and org.lightjason.agentspeak.language.execution.expression.IBaseBinary.variables().